apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: mecominds
data:
  nginx.conf: |
    http { 
     server {
       location /stub_status {
         stub_status on;
         access_log off;
        }
      }
    }
