apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: mecominds
data:
  nginx.conf: |
    worker_processes 1;
    events {
      worker_connections 1024;
    }
    http { 
      server {
        listen 80;
        location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
        }
        location /metrics {
          stub_status on;
          access_log off;
        }
      }
    }
