apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: mecominds
data:
  nginx.conf: |
    worker_processes 1;
    events {
      worker_connections 1024;
    }
    http { 
      server {
        location /metrics/ {
          stub_status on;
          access_log off;
          return 200 "active connections: $connections_active\nserver accepts: $connections_accepted\nserver handled: $connections_handled\n";
        }
        location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
        }
      }
    }
