apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: mecominds
data:
  nginx.conf: |
    worker_processes 1;
    events {
      worker_connections 1024;
    }
    http { 
      server {
        location /metrics/ {
          stub_status on;
          access_log off;
          return 200 "Active connections: $connections_active\nserver accepts handled requests\n$connections_accepted $connections_handled $request_count\nReading: $connections_reading Writing: $connections_writing Waiting: $connections_waiting\n";
        }
        location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
        }
      }
    }
