apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-exporter
spec:
  selector:
    matchLabels:
      app: nginx-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-exporter
    spec:
      containers:
        - name: nginx-exporter
          image: quay.io/prometheus-community/nginx-exporter
          args:
            - "-nginx.scrape-uri=https://mecominds.devops2022.de/status"
          ports:
            - name: http-metrics
              containerPort: 9113
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter
spec:
  selector:
    app: nginx-exporter
  ports:
    - name: http-metrics
      port: 9113
