apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: mecominds
data:
  prometheus.yml: |
    global:
      scrape_interval:     60s
    scrape_configs:
      - job_name: mecominds-nginx
        scheme: https
        scrape_interval: 10s
        metrics_path: "/index.html"
        static_configs:
        - targets: 
          - mecominds.devops2022.de
