apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: mecominds
data:
  prometheus.yml: |
    global:
      scrape_interval:     60s
    scrape_configs:
      - job_name: mecominds-nginx-exporter
        scheme: https
        scrape_interval: 5s
        metrics_path: "/metrics"
        static_configs:
        - targets: ['localhost:9113']
