<<<<<<< HEAD
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: mecominds
data:
  prometheus.yml: |
    global:
      scrape_interval:     60s
    scrape_configs:
      - job_name: mecominds-nginx
        scheme: https
        scrape_interval: 10s
        metrics_path: "/metrics/"
        static_configs:
        - targets: 
          - mecominds.devops2022.de
=======
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: mecominds
data:
  prometheus.yml: |
    global:
      scrape_interval:     60s
    scrape_configs:
      - job_name: mecominds-nginx
        scheme: https
        scrape_interval: 10s
        metrics_path: "/"
        static_configs:
        - targets: 
          - mecominds.devops2022.de
>>>>>>> 530d95739ec917959c2023a4154260bc56064085
