apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: devops2022.azurecr.io/mecominds:a4af8977c8923c5a1a276dedd07ff8e82d20681e
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx
        - name: nginx-prometheus-exporter
          image: nginx/nginx-prometheus-exporter
          ports:
            - containerPort: 9113
          args:
            - -nginx.scrape-uri=https://mecominds.devops2022.de/nginx_status
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
    - name: nginx-prometheus-exporter
      port: 9113
      targetPort: 9113
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/auth-response-headers: X-Forwarded-Proto,Referer
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - mecominds.devops2022.de
      secretName: tls
  rules:
    - host: mecominds.devops2022.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: grafana-service
                port:
                  number: 3000
            nginx:
              rewrite_target: /grafana
              proxy_cookie_path: /grafana/ /
              proxy_set_header:
                Referer: $http_referer
                X-Forwarded-Proto: $scheme
          - path: /kibana
            pathType: Prefix
            backend:
              service:
                name: kibana-kb-http
                port:
                  number: 5601
          - path: /prometheus
            pathType: Prefix
            backend:
              service:
                name: prometheus-service
                port:
                  number: 9090
