apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: mecominds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
      annotations:
        nginx.ingress.kubernetes.io/auth-response-headers: X-Forwarded-Proto,Referer
        nginx.ingress.kubernetes.io/auth-url: "https://mecominds.devops2022.de/_oauth2/auth"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header Referer $http_referer;
          proxy_cookie_path / /grafana/;
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - name: grafana
              containerPort: 3000
          volumeMounts:
            - mountPath: /etc/grafana/provisioning/datasources
              name: grafana-datasources
              readOnly: false
      volumes:
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: mecominds
spec:
  selector:
    app: grafana
  ports:
    - name: grafana
      port: 3000
      targetPort: grafana
